export const WebhookField = {
    Messages: 'messages',
    AccountUpdate: 'account_update',
    AccountReviewUpdate: 'account_review_update',
    AccountAlerts: 'account_alerts',
    AccountSettingsUpdate: 'account_settings_update',
    BusinessCapabilityUpdate: 'business_capability_update',
    BusinessStatusUpdate: 'business_status_update',
    PhoneNumberNameUpdate: 'phone_number_name_update',
    PhoneNumberQualityUpdate: 'phone_number_quality_update',
    MessageTemplateStatusUpdate: 'message_template_status_update',
    MessageTemplateQualityUpdate: 'message_template_quality_update',
    MessageTemplateComponentsUpdate: 'message_template_components_update',
    TemplateCategoryUpdate: 'template_category_update',
    TemplateCorrectCategoryDetection: 'template_correct_category_detection',
    Flows: 'flows',
    Security: 'security',
    History: 'history',
    SmbMessageEchoes: 'smb_message_echoes',
    SmbAppStateSync: 'smb_app_state_sync',
    AutomaticEvents: 'automatic_events',
    TrackingEvents: 'tracking_events',
    Calls: 'calls',
    GroupLifecycleUpdate: 'group_lifecycle_update',
    GroupParticipantsUpdate: 'group_participants_update',
    GroupSettingsUpdate: 'group_settings_update',
    GroupStatusUpdate: 'group_status_update',
    MessageEchoes: 'message_echoes',
    MessagingHandovers: 'messaging_handovers',
    PartnerSolutions: 'partner_solutions',
    PaymentConfigurationUpdate: 'payment_configuration_update',
    Standby: 'standby',
    UserPreferences: 'user_preferences',
} as const;

export type WebhookFieldType = (typeof WebhookField)[keyof typeof WebhookField];
