openapi: 3.0.0

info:
  title: Meta Cloud API
  version: 1.0.0
  description: API documentation for WhatsApp Cloud API

tags:
  - name: Messages
    description: API documentation for WhatsApp messages
  - name: Templates
    description: API documentation for WhatsApp message templates
  - name: Media
    description: API endpoints for uploading, retrieving, and managing WhatsApp media files
  - name: QR Codes
    description: API endpoints for creating and managing WhatsApp QR codes
  - name: WABA
    description: API endpoints for WhatsApp Business Account (WABA) management
  - name: Phone Numbers
    description: API endpoints for managing and verifying WhatsApp business phone numbers
  - name: Registration
    description: API endpoints for registering and deregistering WhatsApp phone numbers
  - name: Encryption
    description: API endpoints for managing WhatsApp business encryption keys
  - name: Two-Step Verification
    description: API endpoints for configuring two-step verification for WhatsApp business accounts

servers:
  - url: https://graph.facebook.com/{version}
    variables:
      version:
        default: v22.0
        description: Meta Graph API version
    description: Meta Cloud API production server

externalDocs:
  description: Find out more about Meta Cloud API
  url: https://developers.facebook.com/docs/whatsapp/cloud-api/reference/