import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    docsSidebar: [
        'intro',
        'get-started',
        {
            type: 'category',
            label: 'API Reference',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'api-reference',
                },
            ],
        },
        {
            type: 'category',
            label: 'Tutorials',
            items: [{ type: 'autogenerated', dirName: 'tutorials' }],
        },
        'settings',
    ],
};

export default sidebars;
