openapi: 3.0.0
components:
  schemas:
    Error:
      description: Error response
      type: object
      required:
        - error
      properties:
        error:
          type: object
          properties:
            code:
              type: integer
              description: Error code
            message:
              type: string
              description: Error message
            type:
              type: string
              description: Error type
            error_data:
              type: object
              description: Additional error data
              
    #######################
    # Template related Schemas
    #######################
    TemplateStatusEnum:
      type: string
      enum:
        - APPROVED
        - PENDING
        - REJECTED
      description: Status of the template
    
    LanguagesEnum:
      type: string
      enum:
        - en
        - en_US
        - fr
        - de
        - es
        - it
        - pt_BR
        - ar
        - hi
        - id
        - ja
        - ko
        - ru
        - tr
        - zh_CN
        - zh_TW
      description: Available languages for templates
    
    CategoryEnum:
      type: string
      enum:
        - AUTHENTICATION
        - MARKETING
        - UTILITY
      description: Category of the template
    
    MessageTypesEnum:
      type: string
      enum:
        - TEXT
        - IMAGE
        - DOCUMENT
        - VIDEO
        - LOCATION
      description: Message format types
    
    RequestCodeMethodsEnum:
      type: string
      enum:
        - SMS
        - VOICE
      description: Methods to receive verification code 