openapi: 3.0.0

info:
  title: Meta Cloud API - Templates
  version: 1.0.0
  description: API documentation for WhatsApp message templates

tags:
  - name: Messages
    description: API documentation for WhatsApp messages
  - name: Templates
    description: API documentation for WhatsApp message templates

servers:
  - url: http://localhost:8080


externalDocs:
  description: Find out more about Meta Cloud API
  url: https://developers.facebook.com/docs/whatsapp/cloud-api/reference/