openapi: 3.0.0
info:
  title: Meta Cloud API
  version: 1.0.0
  description: API documentation for Meta Cloud APIs

tags:
  - name: Messages
    description: API documentation for WhatsApp messages
  - name: Templates
    description: API documentation for WhatsApp message templates
  - name: Phone Numbers
    description: API documentation for WhatsApp phone numbers
  - name: QR Codes
    description: API documentation for WhatsApp QR codes
  - name: WABA
    description: API documentation for WhatsApp Business API subscriptions
  - name: Encryption
    description: API documentation for WhatsApp business encryption
  - name: Two-Step Verification
    description: API documentation for WhatsApp two-step verification
  - name: Media
    description: API documentation for WhatsApp media

servers:
  - url: http://localhost:8080

externalDocs:
  description: Find out more about Meta Cloud API
  url: https://developers.facebook.com/docs/whatsapp/cloud-api/reference/ 