name: CI

on:
  pull_request:
    paths:
      - 'packages/ui/**'
      - 'apps/**'

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version-file: .nvmrc
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm --filter="...[origin/${{ github.base_ref }}]" lint
      - name: Type check
        run: pnpm --filter="...[origin/${{ github.base_ref }}]" typecheck
      - name: Build
        run: pnpm --filter="...[origin/${{ github.base_ref }}]" build
